# Welcome to Impatient-Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically.

# Site settings
title: Freelance Igniter
email: bdavidxyz@gmail.com
description: > # this means to ignore newlines until "twitter_username:"
  Se lancer en indépendant, ou se lancer comme freelance, c'est assez exigeant, particulièrement sur le volet commercial. J'aide les développeurs à devenir indépendant.
twitter_username: bdavidxyz
github_username:  bdavidxyz

# Build settings
markdown: kramdown

# Exclude nodes artifacts from build
exclude:
  - package.json
  - node_modules
  - gulpfile.js
